name : sigmahawk-docker
services :
  db :
    image : postgres
    restart : always
    shm_size : 128mb
    environment :
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_USER: sigma
      POSTGRES_DB: sigmadb
    ports :
      - 5432:5432
    volumes :
      - pgdata:/var/lib/postgresql/data

  pgadmin :
    image : dpage/pgadmin4
    restart : always
    environment :
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports :
      - 5050:80
    depends_on :
      - db

volumes:
  pgdata:
